# Generated by Django 3.1.4 on 2020-12-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Produto',
        ),
    ]
