# Generated by Django 3.1.4 on 2020-12-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtos'),
        ('produtos', '0002_auto_20201227_2248'),
    ]

    operations = [
    ]
